### ISSUE TITLE
Mistakes in the README.md file

### ISSUE THREAD

**Issue by maseev** [networknt/microservices-framework-benchmark#35]
"sprin**t**-boot" -> "sprin**g**-boot"
https://github.com/networknt/microservices-framework-benchmark/blame/master/README.md#L126

"th**e**n" -> "th**a**n"
https://github.com/networknt/microservices-framework-benchmark/blame/master/README.md#L126
https://github.com/networknt/microservices-framework-benchmark/blame/master/README.md#L246

**Comment by stevehu** [comment]
@maseev thanks for the catch. I will fix them once I can access my computer next week.

**Comment by stevehu** [comment]
@maseev I have updated the README.md and checked in. Thanks a lot for your help.
