### ISSUE TITLE
The scoreboard missing JFinal, ninjaframework and Play1 result

### ISSUE THREAD

**Issue by greenlaw110** [networknt/microservices-framework-benchmark#5]
@stevehu are you going to run those tests?

**Comment by stevehu** [comment]
JFinal and NinjaFramework are done. Do you think we need play1 to be there when everyone is using play2? My first impression is hard to build:)

**Comment by greenlaw110** [comment]
AFAIK there are still a lot of person hangling on play1 simply because they don't like play2. It's actually very easy to play with play1. Just download their package from http://playframework.com. Unzip it, add it to your PATH variable, then inside the play1 testing project, type `play run --%prod`

**Comment by stevehu** [comment]
I have added the result for play1. Thanks for your help.
