### ISSUE TITLE
Adding node-uws

### ISSUE THREAD

**Issue by gonzalovazquez** [networknt/microservices-framework-benchmark#7]
Hi Steve,

I created a pull request to add[ node-uws](https://github.com/uWebSockets/uWebSockets) to your benchmarking chart. When I ran the benchmark these were my results:
```
➜  microservices-framework-benchmark git:(node-uws) ✗ wrk -t4 -c128 -d30s http://localhost:8080 -s pipeline.lua --latency -- / 16
Running 30s test @ http://localhost:8080
  4 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.10ms    3.04ms 158.86ms   94.97%
    Req/Sec   101.15k    19.90k  172.61k    80.58%
  Latency Distribution
     50%    2.70ms
     75%    4.00ms
     90%    5.09ms
     99%   14.53ms
  12080368 requests in 30.02s, 587.56MB read
  Socket errors: connect 0, read 332, write 0, timeout 0
Requests/sec: 402470.06
Transfer/sec:     19.58MB
```

If you get similar results this would put node-uws right under Go Iris.

To build:

```
cd node-uws
```
```
make
```
```
node server.js
```

Let me know if you are interested in adding it.

Gonzalo

**Comment by stevehu** [comment]
This is big improvement on top of nodejs. My desktop might be a little slower as I am using an aging i5 cpu with only 4 cores and 4 thread to simulate a typical cloud VM. I think you forget to submit the pull request:)

Thanks.

**Comment by gonzalovazquez** [comment]
Here it is!

https://github.com/networknt/microservices-framework-benchmark/pull/8

Thanks.

**Comment by stevehu** [comment]
I've got the following error when trying to start the serve with node v5.3.0. Is a particular version of node required? Thanks.
```
steve@joy:~/networknt/microservices-framework-benchmark/node-uws$ node server.js
/home/steve/networknt/microservices-framework-benchmark/node-uws/server.js:4
const document = Buffer.from('Hello world!');
                        ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/steve/networknt/microservices-framework-benchmark/node-uws/server.js:4:25)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by gonzalovazquez** [comment]
I was able to run it with node v6.3.1

**Comment by stevehu** [comment]
Yes. it works with node v6.3.1 and I have published the result which is similar with yours. Thanks a lot for your help.

**Comment by gonzalovazquez** [comment]
Glad to help!
